Change the build pack to fail if the makefile fails

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -185,10 +185,17 @@ mkdir -p $BUILD_DIR/.profile.d
 echo "export PATH=\"\$HOME/bin:\$HOME/node_modules/.bin:\$PATH\"" > $BUILD_DIR/.profile.d/nodejs.sh
 
 # If a makefile exists, there are extra custom build steps (e.g. jshint,
-# minification, validation checks, etc.) that need to be run.  Makefile
-# should look at ENV to determine release vs. debug.
+# minification, validation checks, etc.) that need to be run.
 echo "-----> Building runtime environment"
 if [ -f $BUILD_DIR/Makefile ]; then
 	echo "-----> Makefile detected. Running make"
-	cd $BUILD_DIR; make
+	cd $BUILD_DIR
+	# Makefile should look at ENV to determine release vs. debug.
+	make
+
+	# If make fails, the compilation of the build fails. Don't deploy!
+	if [ $? -ne 0 ]; then
+		echo "Buildpack compilation failure: Makefile failed.
+		exit $?
+	fi
 fi
